### PR TITLE
2024秋冬训练营_孙宇航_Blog

### PR DESCRIPTION
**Pull request by DaZhou-ECHO**
# 第一阶段和第二阶段的Blog
包含完成两个阶段的心路历程和相关实践

### CODE REVIEW

**Comment by DaZhou-ECHO** [comment]
@hky1999  Could you please review and process my PR? Thank you!

**Comment by hky1999** [comment]
> @hky1999 Could you please review and process my PR? Thank you!

please update your PR yourself, just revert your modification to un-related files and re-push to this branch

**Comment by DaZhou-ECHO** [comment]
@hky1999  Could you please check if this modification meets the requirements? Thank you very much

> > @hky1999 Could you please review and process my PR? Thank you!
> 
> please update your PR yourself, just revert your modification to un-related files and re-push to this branch

**Review by hky1999 — APPROVED** [review]
LGTM

**Pull request merged**
